name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug, release, split)'
        required: true
        default: 'release'
        type: choice
        options:
        - debug
        - release
        - split

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
      
    - name: Configure Flutter for Android only
      run: |
        flutter config --no-enable-web
        flutter config --enable-android
    
    - name: Run tests
      run: flutter test
      continue-on-error: true
    
    - name: Build APK (Debug)
      if: github.event.inputs.build_type == 'debug' || github.event.inputs.build_type == ''
      run: |
        flutter build apk --debug --verbose
    
    - name: Build APK (Release)
      if: github.event.inputs.build_type == 'release' || github.event.inputs.build_type == ''
      run: |
        flutter build apk --release --verbose
    
    - name: Build Split APKs
      if: github.event.inputs.build_type == 'split' || github.event.inputs.build_type == ''
      run: |
        flutter build apk --split-per-abi --verbose
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
      continue-on-error: true
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
      continue-on-error: true
    
    - name: Upload Split APKs
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: split-apks
        path: build/app/outputs/flutter-apk/
      continue-on-error: true
