name: Build APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.24.5'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Run tests
      run: flutter test
      continue-on-error: true
    
    - name: Build APK (Debug)
      run: flutter build apk --debug
      continue-on-error: true
    
    - name: Build APK (Release)
      run: flutter build apk --release
      continue-on-error: true
    
    - name: Build Split APKs
      run: flutter build apk --split-per-abi
      continue-on-error: true
    
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: debug-apk
        path: build/app/outputs/flutter-apk/app-debug.apk
      continue-on-error: true
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk
      continue-on-error: true
    
    - name: Upload Split APKs
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: split-apks
        path: build/app/outputs/flutter-apk/
      continue-on-error: true
