name: Build APK - WORKING VERSION

on:
  workflow_dispatch: # Manual trigger only

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.10.6'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Build Release APK
      run: |
        flutter build apk --release
        echo "✅ Build completed successfully!"
        ls -la build/app/outputs/flutter-apk/
        echo "📱 APK files:"
        find build/ -name "*.apk" -type f

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: warehouse-inventory-app
        path: build/app/outputs/flutter-apk/*.apk
        retention-days: 30
