name: Build APK - Final Working Version

on:
  workflow_dispatch:

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup Java 8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '8'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.13.9'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
      
    - name: Show versions
      run: |
        flutter --version
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
    
    - name: Clean and build APK
      run: |
        flutter clean
        flutter pub get
        flutter build apk --release
        echo "Build completed successfully!"
        ls -la build/app/outputs/flutter-apk/
        echo "APK files found:"
        find build/ -name "*.apk" -type f
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: warehouse-inventory-app
        path: build/app/outputs/flutter-apk/*.apk
        retention-days: 30
