name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '11'
    
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
        cache: true
    
    - name: Install dependencies
      run: flutter pub get
      
    - name: Show Flutter and Java versions
      run: |
        flutter --version
        java -version
        echo $JAVA_HOME
    
    - name: Run tests
      run: flutter test
      continue-on-error: true
    
    - name: Clean build directory
      run: flutter clean
    
    - name: Build Debug APK
      run: |
        flutter build apk --debug
        ls -la build/app/outputs/flutter-apk/
      continue-on-error: false
    
    - name: List Debug APK files
      run: find build/ -name "*.apk" -type f
      
    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: warehouse-inventory-debug
        path: build/app/outputs/flutter-apk/*.apk
        retention-days: 7
      continue-on-error: true
    
    - name: Clean build directory for release
      run: flutter clean
    
    - name: Build Release APK
      run: |
        flutter build apk --release
        ls -la build/app/outputs/flutter-apk/
      continue-on-error: false
    
    - name: List Release APK files
      run: find build/ -name "*.apk" -type f
    
    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: warehouse-inventory-release
        path: build/app/outputs/flutter-apk/*.apk
        retention-days: 7
      continue-on-error: true